version: "3.8"
services:
  ingester:
    build:
      context: ingester
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
    restart: on-failure
    depends_on:
      - kafka
      - elasticsearch
      - cassandra
    environment:
      KAFKA_HOST: kafka:9092
      CASSANDRA_HOST: cassandra:9042
      ELASTICSEARCH_HOST: elasticsearch:9200
    networks:
      - ingester-network

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - kafka
      - elasticsearch
      - cassandra
    environment:
      KAFKA_HOST: kafka:9092
      CASSANDRA_HOST: cassandra:9042
      ELASTICSEARCH_HOST: elasticsearch:9200
    networks:
      - ingester-network

  elasticsearch:
    image: elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ingester-network

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./scripts/setup-cassandra:/docker-entrypoint-initdb.d
    networks:
      - ingester-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "log-topic:1:1"
    networks:
      - ingester-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ingester-network

volumes:
  cassandra_data:
  elasticsearch-data:

networks:
  ingester-network:
